const products = [
  {
    id: 1,
    name: "Simple Modern School Boys",
    category: ["Backpack", "Wonder"],
    price: 94.0,
    originalPrice: 100.0,
    rating: 5,
    image: "/item1.png",
  },
  {
    id: 2,
    name: "Women's Essentials Convertible",
    category: ["Shoe", "Men's"],
    price: 126.0,
    originalPrice: 216.0,
    rating: 4,
    image: "/item2.png",
  },
  {
    id: 3,
    name: "Calvin Klein Gabrianna Novelty",
    category: ["Bag", "Wonder"],
    price: 93.0,
    originalPrice: 176.0,
    rating: 5,
    image: "/item3.png",
  },
  {
    id: 4,
    name: "Adidas Running Shoes",
    category: ["Shoe", "Sports"],
    price: 140.0,
    originalPrice: 180.0,
    rating: 4,
    image: "/item4.png",
  },
  {
    id: 5,
    name: "Leather Laptop Backpack",
    category: ["Bag", "Work"],
    price: 190.0,
    originalPrice: 250.0,
    rating: 3,
    image: "/item5.png",
  },
  {
    id: 6,
    name: "Nike Air Max Sneakers",
    category: ["Shoe", "Men's"],
    price: 160.0,
    originalPrice: 220.0,
    rating: 5,
    image: "/item6.png",
  },
  {
    id: 7,
    name: "Summer Beach Tote Bag",
    category: ["Bag", "Summer"],
    price: 550.0,
    originalPrice: 700.0,
    rating: 4,
    image: "/item7.png",
  },
];

export default products;
